### ISSUE TITLE
实例显示

### ISSUE THREAD

**Issue by kangpou** [Ernest-su/LinuxCmd#22]
APP里实例没有显示，是不是没更新，希望抽空更新一波。原网址是有实例显示的 https://wangchujiang.com/linux-command/c/find.html
![IMG_20221026_055639](https://user-images.githubusercontent.com/85426107/197890343-5a79158c-24f9-4960-94f3-5e4493e047f0.jpg)

**Comment by Ernest-su** [comment]
已修复
